esphome:
  name: solar-system
  friendly_name: Solar inverter system
  devices:   
    - id: inverter
      name: "Deye inverter"
    - id: bms1
      name: "bms1"
    - id: bms2
      name: "bms2" 
    - id: bms3
      name: "bms3"
    - id: bms4
      name: "bms4"    
    - id: bms5
      name: "bms5"     
    - id: bms6
      name: "bms6" 
    - id: bms7
      name: "bms7"    
    - id: bms8
      name: "bms8"     
    - id: bms9
      name: "bms9"     
    - id: bms10
      name: "bms10"         
   
  on_boot:
    - priority: 600  # Chạy ngay khi linh kiện vừa khởi tạo xong
      then:
        - light.turn_on:
            id: rgb_led
            red: 100%
            green: 100%
            blue: 0%
            brightness: 80%
        - delay: 3s    # Chờ 3 giây
        - light.turn_off: rgb_led # Tắt đèn sau khi hết 3 giây
        - script.execute: wifi_led

    - priority: -100   # chạy sau khi đã khởi tạo component
      then:   
        - logger.set_level: INFO
        - select.set:
            id: log_level
            option: INFO        

esp32:
  variant: esp32s3
  framework:
    type: arduino    
psram:
  mode: octal

logger:
  level: DEBUG
  tx_buffer_size: 2048
  hardware_uart: UART0

api:
  encryption:
    key: "Ph+dnuYMuYAGPmuLLf27izS6nKobWSIpRhZUK75qB14="

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  on_connect:
    then:
      - script.execute: wifi_led    

  on_disconnect:
    then:
      - script.execute: wifi_led
  ap:
    ssid: jk bms Fallback Hotspot
    password: "12345678"    

captive_portal:
  
time:
  - platform: sntp
    
#================= RGB =================#
light:
  - platform: esp32_rmt_led_strip
    name: "ESP32S3 RGB"
    id: rgb_led
    channel_colors: GRB
    pin: GPIO48
    chipset: WS2812      
    num_leds: 1
    effects:
      - strobe:
          name: "Blink Blue"
          colors:
            - state: true
              brightness: 80%
              red: 0%
              green: 0%
              blue: 100%
              duration: 0.5s
            - state: false
              duration: 0.5s     
              
#================= SCRIPT=================#
script:
  - id: wifi_led
    mode: restart
    then:
      - if:
          condition:
            wifi.connected:
          then:
            - light.turn_on:
                id: rgb_led
                red: 0%
                green: 0%
                blue: 100%
                effect: none
                brightness: 50%
          else:
            - light.turn_on:
                id: rgb_led      
                effect: "Blink Blue"       
                
################### ESP CPU CONFIGS ####################  
text_sensor:
  - platform: uptime
    name: "Uptime"
    
  - platform: wifi_info
    ssid:
      name: "WiFi SSID"
      icon: mdi:wifi-sync

  - platform: wifi_info
    ip_address:
      name: "IP Address"
      icon: mdi:ip-network-outline

  - platform: wifi_info
    bssid:
      name: "BSSID"  
      icon: mdi:wifi-marker

  - platform: wifi_info
    mac_address:
      name: "MAC"  
      icon: mdi:wifi-marker      

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
   
  - platform: internal_temperature  
    name: "CPU Temp"   

button:
  - platform: restart
    name: "Restart"
    icon: mdi:restart
    
  - platform: factory_reset
    name: "Factory Reset (Eraser All Data)"    
    
################### SET REALTIME LOG LEVEL ####################    
select:
  - platform: template
    name: "Log Level"
    icon: mdi:android
    id: log_level
    optimistic: true
    restore_value: true
#    initial_option: INFO
    entity_category: config
    options:
      - ERROR
      - WARN
      - INFO
      - DEBUG   
      - VERBOSE
      - VERY_VERBOSE        

    set_action:
      - if:
          condition:
            lambda: return x == "ERROR";
          then:
            - logger.set_level: ERROR

      - if:
          condition:
            lambda: return x == "WARN";
          then:
            - logger.set_level: WARN

      - if:
          condition:
            lambda: return x == "INFO";
          then:
            - logger.set_level: INFO

      - if:
          condition:
            lambda: return x == "DEBUG";
          then:
            - logger.set_level: DEBUG            

      - if:
          condition:
            lambda: return x == "VERBOSE";
          then:
            - logger.set_level: VERBOSE    

      - if:
          condition:
            lambda: return x == "VERY_VERBOSE";
          then:
            - logger.set_level: VERY_VERBOSE                   
              
#================= EXTERNAL COMPONENTS =================#  
external_components:
   - source: github://txubelaxu/esphome-jk-bms@main
     refresh: 0s
     components: [ jk_rs485_sniffer , jk_rs485_bms ]

# ================= UART =================     
uart:
  - id: uart_1    # Inverter      
    tx_pin: GPIO16
    rx_pin: GPIO15
    baud_rate: 9600
    data_bits: 8
    stop_bits: 1
    parity: NONE
  
  - id: uart_2   # JK BMS
    tx_pin: GPIO17
    rx_pin: GPIO18
    baud_rate: 115200
    rx_buffer_size: 512    

# =============== INVERTER MODBUS ============
modbus:
  id: modbus1
  uart_id: uart_1
  send_wait_time: 100ms
  turnaround_time: 100ms

modbus_controller:
  - id: deye
    modbus_id: modbus1
    address: 1
    update_interval: 2s
    
# ================= JK BMS ================= 
jk_rs485_sniffer:
  id: sniffer1
  protocol_version: "JK02_32S"
  rx_timeout: 500ms
  uart_id: uart_2

jk_rs485_bms:
  - id: rs485_bms1
    rs485_address: 0x00
    jk_rs485_sniffer_id: sniffer1
    update_interval: 5s
    
  - id: rs485_bms2
    rs485_address: 0x01
    jk_rs485_sniffer_id: sniffer1
    update_interval: 5s   

  - id: rs485_bms3
    rs485_address: 0x02
    jk_rs485_sniffer_id: sniffer1
    update_interval: 5s      

  - id: rs485_bms4
    rs485_address: 0x03
    jk_rs485_sniffer_id: sniffer1
    update_interval: 5s      

  - id: rs485_bms5
    rs485_address: 0x04
    jk_rs485_sniffer_id: sniffer1
    update_interval: 5s      

  - id: rs485_bms6
    rs485_address: 0x05
    jk_rs485_sniffer_id: sniffer1
    update_interval: 5s     

  - id: rs485_bms7
    rs485_address: 0x06
    jk_rs485_sniffer_id: sniffer1
    update_interval: 5s      

  - id: rs485_bms8
    rs485_address: 0x07
    jk_rs485_sniffer_id: sniffer1
    update_interval: 5s      

  - id: rs485_bms9
    rs485_address: 0x08
    jk_rs485_sniffer_id: sniffer1
    update_interval: 5s    

  - id: rs485_bms10
    rs485_address: 0x09
    jk_rs485_sniffer_id: sniffer1
    update_interval: 5s      

  
switch:
#======= Switch đồng bộ cài đặt các bms ======#    
  - platform: template
    name: "Broadcast changes to all BMSs"
    id: broadcast_active
    icon: "mdi:cast"
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: true
    turn_on_action:
      - lambda: |-
          id(sniffer1).set_broadcast_changes_to_all_bms(true);  
    turn_off_action:
      - lambda: |-
          id(sniffer1).set_broadcast_changes_to_all_bms(false);          


packages:
  inverter: !include 
    file: packages/deyesg05lp1.yaml
    vars:   
      device_id: inverter
      
  bms1: !include 
    file: packages/jk_uart.yaml
    vars:
      jk_rs485_bms_id: rs485_bms1
      device_id: bms1
      name: bms1

  bms2: !include 
    file: packages/jk_uart.yaml
    vars:
      jk_rs485_bms_id: rs485_bms2
      device_id: bms2

  bms3: !include 
    file: packages/jk_uart.yaml
    vars:
      jk_rs485_bms_id: rs485_bms3
      device_id: bms3     

  bms4: !include 
    file: packages/jk_uart.yaml
    vars:
      jk_rs485_bms_id: rs485_bms4
      device_id: bms4
  
  bms5: !include 
    file: packages/jk_uart.yaml
    vars:
      jk_rs485_bms_id: rs485_bms5
      device_id: bms5
  
  bms6: !include 
    file: packages/jk_uart.yaml
    vars:
      jk_rs485_bms_id: rs485_bms6
      device_id: bms6
  
  bms7: !include 
    file: packages/jk_uart.yaml
    vars:
      jk_rs485_bms_id: rs485_bms7
      device_id: bms7
  
  bms8: !include 
    file: packages/jk_uart.yaml
    vars:
      jk_rs485_bms_id: rs485_bms8
      device_id: bms8
  
  bms9: !include 
    file: packages/jk_uart.yaml
    vars:
      jk_rs485_bms_id: rs485_bms9
      device_id: bms9
  
  bms10: !include 
    file: packages/jk_uart.yaml
    vars:
      jk_rs485_bms_id: rs485_bms10
      device_id: bms10    